---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: web-frontend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-frontend
  template:
    metadata:
      labels:
        app: web-frontend
    spec:
      containers:
      - env:
        - name: NGINX_HOST
          value: my-first-web-app.com
        - name: NGINX_PORT
          value: '80'
        image: nginx:latest
        name: web-frontend
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 15
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: web-frontend
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: web-frontend
  type: LoadBalancer
